#!/bin/sh -x 

DUNSTRC="$HOME/.config/dotfiles/dunst/dunstrc"
DUNSTRC_TEMPLATE="$HOME/.config/dotfiles/dunst/dunstrcTemplate"
XRESOURCE_COMMAND="$HOME/.config/dotfiles/lemonbar/get_xresource_value.sh"

BLACK=`$XRESOURCE_COMMAND color0`
DARK_RED=`$XRESOURCE_COMMAND color1`
DARK_GREEN=`$XRESOURCE_COMMAND color2`
DARK_YELLOW=`$XRESOURCE_COMMAND color3`
DARK_BLUE=`$XRESOURCE_COMMAND color4`
DARK_MAGENTA=`$XRESOURCE_COMMAND color5`
DARK_CYAN=`$XRESOURCE_COMMAND color6`
LIGHT_GRAY=`$XRESOURCE_COMMAND color7`
GRAY=`$XRESOURCE_COMMAND color8`
RED=`$XRESOURCE_COMMAND color9`
GREEN=`$XRESOURCE_COMMAND color10`
YELLOW=`$XRESOURCE_COMMAND color11`
BLUE=`$XRESOURCE_COMMAND color12`
MAGENTA=`$XRESOURCE_COMMAND color13`
CYAN=`$XRESOURCE_COMMAND color14`
LIGHT_GRAY=`$XRESOURCE_COMMAND color15`

# define colors
BACKGROUND_COLOR=`$XRESOURCE_COMMAND color0`
LOW_URGENCY_TEXT_COLOR=`$XRESOURCE_COMMAND color7`
LOW_URGENCY_TEXT_COLOR=`$XRESOURCE_COMMAND color7`

# replace background
NEW_DUNST_FILE=`cat $DUNSTRC_TEMPLATE |\
  sed -r "s/FRAME_COLOR_ALL/\"$MAGENTA\"/g"\ |
  sed -r "s/BACKGROUND/\"$BLACK\"/g"\ |
  sed -r "s/LOW_URGENCY_FOREGROUND/\"$DARK_GREEN\"/g"\ |
  sed -r "s/NORMAL_URGENCY_FOREGROUND/\"$DARK_YELLOW\"/g"\ |
  sed -r "s/CRITICAL_URGENCY_FOREGROUND/\"$DARK_RED\"/g"\
  `

echo "$NEW_DUNST_FILE" > $DUNSTRC
