#!/bin/sh -x

EPOCH=`date +%s`
FILE_NAME="$EPOCH-screenshot.png"
SCREENSHOTS_DIR="$HOME/.screenshots"
NOTIFICATION_DAEMON="dunstify"

mkdir -p "$SCREENSHOTS_DIR"

# maim -s "$SCREENSHOTS_DIR/$FILE_NAME"
# wayland
grimblast save area "$SCREENSHOTS_DIR/$FILE_NAME"

# cat "$SCREENSHOTS_DIR/$FILE_NAME" | xclip -sel CLIPBOARD -t image/png
cat "$SCREENSHOTS_DIR/$FILE_NAME" | wl-copy --type image/png

$NOTIFICATION_DAEMON "Screenshot $FILE_NAME copied to clipboard"
