#!/bin/sh -x

EPOCH=`date +%s`
FILE_NAME="$EPOCH-screenshot.png"
SCREENSHOTS_DIR="$HOME/.screenshots"
NOTIFICATION_DAEMON="dunstify"

mkdir -p "$SCREENSHOTS_DIR"

scrot -s "$SCREENSHOTS_DIR/$FILE_NAME"

cat "$SCREENSHOTS_DIR/$FILE_NAME" | xclip -sel CLIPBOARD -t image/png

$NOTIFICATION_DAEMON "Screenshot $FILE_NAME copied to clipboard"
