#!/bin/sh

# restart sxhkd properly
killall sxhkd
sxhkd &

# restart dunst properly
killall dunst

wal -R

# clean all bar-related processes
killall lemonbar
for PID in `ps aux | egrep "lemonbar" | egrep -v "grep" | egrep "\.(sh|py)" | sed -r "s/ +/ /g" | cut -d' ' -f2`
do
  kill -SIGTERM "$PID"
done
$HOME/.config/dotfiles/lemonbar/main.sh &

xrdb -merge ~/.Xresources

bspc monitor -d "1-web" "2-code" "3-servers" # III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12
bspc config focus_follows_pointer true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config top_padding 40

bspc rule -a \* state=tiled

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
