#!/bin/sh

sxhkd &

wal -R

$HOME/.config/dotfiles/lemonbar/main.sh &

bspc monitor -d "1-web" "2-code" "3-servers" # III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12
bspc config focus_follows_pointer true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config top_padding 40

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
